#!/bin/sh
#Script que s'executa en iniciar la sessió X-window (després de lightdm)
#S'executa com a usuari que s'ha loguejat.

#Si debug no està definida, la definim
if [ -z $DEBUG ]; then DEBUG=0; fi
if [ "$DEBUG" -ge 3 ]; then
    # trace output
    set -x
fi

if [ -z $LANG ]; then 
        export LANG=C.UTF-8
fi

logger -t "linuxcaib-xsession-89caib($USER)"  "uid=$(id -u) Feim login de XSession (home=$HOME)"

#Si no hi ha usuari és un canvi dins del greeter que no cal fer res. 
if [ "$USER" != "" ];then

	BASEDIR=$(dirname $0)
	BASEDIRRDLINK=$( readlink "$BASEDIR""$0")
	[ "$DEBUG" -gt "0" ] && echo "BASEDIR=$BASEDIR  BASEDIRRDLINK=$BASEDIRRDLINK"
	[ "$DEBUG" -gt "0" ] && logger -t "linuxcaib-xsession-89caib($USER)" "BASEDIR=$BASEDIR  BASEDIRRDLINK=$BASEDIRRDLINK"

	#Si tenim sessió de seycon/mazinger significa que esteim dins la xarxa de la CAIB
	MZN_SESSION=$(cat $HOME/.caib/MZN_SESSION 2> /dev/null)
	if [ "$MZN_SESSION"  = "" ];then
		logger -t "linuxcaib-xsession-89caib($USER)" "WARN: No hi ha sessió de seycon, no feim rés."
		zenity --info --timeout 3 --title="desconnectat de la xarxa"  --text="Us trobau desconnectats de la xarxa" 
	else
		logger -t "linuxcaib-xsession-89caib($USER)" "INFO: Sessió SEYCON, executam login de les xsession."
		. /opt/caib/linuxcaib/caib-xsession-login.sh
	fi

fi

if [ "$LANG" = "C.UTF-8" ];then
        unset LANG
fi
