#!/bin/sh

#Script que intenta emular la política de AD: Hide Settings tab
#Setting Path:
#User Configuration/Administrative Templates/Control Panel/Display

#Explanation
#This setting prevents users from using Control Panel to add, configure, or change the display settings on the computer.

#TODO: Hauria de deshabilitar el /usr/share/applications/gnome-display-panel.desktop
#tal volta fent un override dins $HOME/.config/apps

