#!/bin/sh

#Script que intenta emular la política de AD: Remove programs on Settings menu
#Setting Path:
#User Configuration/Administrative Templates/Start Menu and Taskbar

#Explanation
#Prevents Control Panel, Printers, and Network Connections from running.
#This setting removes the Control Panel, Printers, and Network and Connection folders from Settings on the Start menu, and from My Computer and Windows Explorer. It also #prevents the programs represented by these folders (such as Control.exe) from running.
#However, users can still start Control Panel items by using other methods, such as right-clicking the desktop to start Display or right-clicking My Computer to start System.
#Also, see the "Disable Control Panel," "Disable Display in Control Panel," and "Remove Network Connections from Start Menu" settings.


#TODO: ocultar el menu "parametres del sistema" i fer que l'usuari no pugui executar gnome-settings etc.
#http://askubuntu.com/questions/442520/is-it-possible-to-remove-items-from-system-settings
#dpkg-statoverride --update --add root root 640 /usr/share/applications/gnome-printers-panel.desktop
#dpkg-statoverride --update --add root root 640 /usr/share/applications/gnome-info-panel.desktop
#dpkg-statoverride --update --add root root 640 /usr/share/applications/gnome-keyboard-panel.desktop
#Per tornar endarrera:
#dpkg-statoverride --remove /usr/share/applications/gnome-keyboard-panel.desktop
#chmod 644 /usr/share/applications/gnome-keyboard-panel.desktop

#Es problema de fer-ho així és que se canvia per a TOTS els usuaris.
#El que cal fer és un override de cada un dels .desktop dins $HOME/.config/applications/...


