#!/bin/sh

#Aqui hi ha diverses configuracions particulars de GNU/Linux
#que no tenen un mapeig directe a cap política de AD

#Que no soni la campana
gsettings set org.gnome.desktop.wm.preferences audible-bell false

#Que nautilus demani donar opció de veure o executar un script de shell (amb permissos d'execució)
gsettings set org.gnome.nautilus.preferences executable-text-activation 'ask'

#Deshabilitar tabulador i emprar espais al gedit
gsettings set org.gnome.gedit.preferences.editor insert-spaces true
gsettings set org.gnome.gedit.preferences.editor tabs-size 'uint32 8'
gsettings set org.gnome.gedit.preferences.editor create-backup-copy false

#Feim que apareixi la paperera de reciclatge
gsettings set org.gnome.nautilus.desktop trash-icon-visible true


#Feim que al menu de sistema no surti la llista d'usuaris locals (hauria d'estar locked)
gsettings set com.canonical.indicator.session user-show-menu false
#Feim que al menu de sistema apareixi el nom de l'usuari (codi usuari seycon) (hauria d'estar locked)
gsettings set com.canonical.indicator.session show-real-name-on-panel true

logger -t "linuxcaib-ad-policies($USER): caib-conf-all-user" -s "Fi" 
