#!/bin/sh

#Script que intenta emular la política de AD: Remove Run menu from Start Menu
#Setting Path:
#User Configuration/Administrative Templates/Start Menu and Taskbar

#Explanation
#If you enable this setting, the following changes occur:
#(1) The Run command is removed from the Start menu.
#(2) The New Task (Run) command is removed from Task Manager.
#(3) The user will be blocked from entering the following into the Internet Explorer Address Bar:
#--- A UNC path: \\<server>\<share> 
#---Accessing local drives: e.g., C:
#--- Accessing local folders: e.g., \temp>
#Also, users with extended keyboards will no longer be able to display the Run dialog box by pressing the Application key (the key with the Windows logo) + R.
#If you disable or do not configure this setting, users will be able to access the Run command in the Start menu and in Task Manager and use the Internet Explorer Address Bar.

#TODO: deshabilitar els terminals que hi hagi instal·lats mitjançant .desktop locals a l'usuari.

#Si tenim permissos d'administrador o tenim el role pcfgtot podrem emprar el run-menu
if [ "$(groups $USER |grep -q pcfgtot && echo "SI")" = "SI" -o "$(groups $USER |grep -q sudo && echo "SI")" ];then
        gsettings set org.gnome.desktop.lockdown disable-command-line false
        logger -t "linuxcaib-ad-policy: disable-run-menu($USER)" -s "Habilitat run-menu"
else
        gsettings set org.gnome.desktop.lockdown disable-command-line true
        logger -t "linuxcaib-ad-policy: disable-run-menu($USER)" -s "deshabilitat run-menu"

fi




