#!/bin/sh

#Script que intenta emular la política de AD: Software\Microsoft\Windows\CurrentVersion\Policies\Network\NoFileSharingControl


#TODO: no se pot des-habilitar la compartició de fitxers via samba des de dconf.
#l'únic que se pot fer és assegurar-se que l'usuari no pertany al grup "sambashare"

#if [ "$(groups $USER |grep -q sambashare && echo "SI")" = "SI" ];then
#        deluser --quiet $USER sambashare
#        logger -t "ad-policy: disable-file-sharing($USER)" -s "INFO: No pot compartir via samba"
#else
#        logger -t "ad-policy: disable-file-sharing($USER)" -s "INFO: Pot compartir via samba"
#fi


logger -t "linuxcaib-ad-policies($USER): disable-file-sharing" -s "PENDENT"

