#!/bin/sh

#Script que intenta emular la política de AD: Disable-screensaver-settings

#Aquesta política no cal, ja que l'escript "caib-conf-screensaver" du a terme
#aquesta funcionalitat
#org.gnome.desktop.session idle-delay
#org.gnome.desktop.screensaver lock-enabled


