#!/bin/sh

#Script que deshabilita el montatge de dispositius USB


if [ "$(groups $USER | grep -q punitot2 && echo "SI")" = "SI" ];then
        gsettings set org.gnome.desktop.media-handling automount-open true
        gsettings set org.gnome.desktop.media-handling automount true
else
        gsettings set org.gnome.desktop.media-handling automount-open false
        gsettings set org.gnome.desktop.media-handling automount false
        logger -t "linuxcaib-ad-policies($USER): disable-media-mount" -s "deshabilitat automontatge d'unitats"
fi

#Només permetem auto executar si té permissos de sudo

if [ "$(groups $USER | grep -q sudo && echo "SI")" = "SI" ];then
        gsettings set org.gnome.desktop.media-handling autorun-never false
else
        logger -t "linuxcaib-ad-policies($USER): disable-media-mount" -s "deshabilitat autorun"
        gsettings set org.gnome.desktop.media-handling autorun-never true
fi
logger -t "linuxcaib-ad-policies($USER): disable-media-mount" -s "Fi" 
