#!/bin/sh

#Script que intenta emular la política de AD: Interactive logon: "Prevent addition of printers" i "Prevent deletion of printers"


if [ "$(groups $USER |grep -q pcfgtot && echo "SI")" = "SI" ];then
        gsettings set org.gnome.desktop.lockdown disable-print-setup false
        logger -t "linuxcaib-ad-policy: disable-printer-setup($USER)" -s "Habilitat printer-setup"
else
        logger -t "linuxcaib-ad-policy: disable-printer-setup($USER)" -s "Deshabilitat printer-setup"
        gsettings set org.gnome.desktop.lockdown disable-print-setup true
fi

