#!/bin/sh

#Script que intenta emular la política de AD: Prevent grouping of taskbar items

#Explanation
#This setting effects the taskbar buttons used to switch between running programs.
#Taskbar grouping consolidates similar applications when there is no room on the taskbar. It kicks in when the user's taskbar is full.
#If you enable this setting, it prevents the taskbar from grouping items that share the same program name. By default, this setting is always enabled.
#If you disable or do not configure it, items on the taskbar that share the same program are grouped together. The users have the option to disable grouping if they choose.

#Això hi ha alguna opció del dconf però ara no la trob.

#A Unity això no es pot fer per disseny.

#Això no funciona, diu que l'schema no existeix! 
#gsettings set org.gnome.gnome-panel.layout.objects.window-list-0.instance-config group-windows 'never-group'
