#!/bin/sh
set -x

#Script que intenta emular la política de AD: Interactive logon: Prompt user to change password before expiration 2 days
# Mirar si falten només 5 dies o manco per expirar la contrasenya.
# Si falten entre 3 i 5 dies, mostrar pantalla per a que l'usuari trii si la vol canviar ara o no.
# Si falten menos de 3 dies, obligar al canvi de contrasenya.

#Pel canvi de contrasenya empram l'script: /opt/caib/linuxcaib/caib-conf-chgpasswd.sh
#Altra opció és obrir la web https://intranet.caib.es/Intranet/canviapassword.do

#Nombre de dies de caducitat de contrasenya
maximumAgePassword=45

#Aquest script mostra (via echo) el text "changed" si l'usuari ha canviat correctament la contrasenya i "password not changed" en cas contrari.
#IMPORTANT: és l'únic que ha de sortir per stdout.

# L'script que crida és el responsable de reiniciar/sortir sessió.
# IMPORTANT: aquest script NOMÉS ha de treure per STDOUT "changed" o "password not changed"
canviar_password () {
        statusfile=$(mktemp)
        xterm -e sh -c 'caib-chgpasswd; echo $? > '$statusfile
        resultChgPasswd=$(cat $statusfile)
        rm $statusfile
        logger -t "prompt-chgpasswd-before-expiration" "DEBUG: resultTxt de canviar password=$resultTxt $resultChgPasswd"
        if [ "$resultChgPasswd" = "0" ];then
                zenity --timeout 10 --width=400 --info --title="Accés a la xarxa corporativa" --text="Heu actualitzat la contrasenya correctament\n\nRecordau a canviar la contrasenya abans de $maximumAgePassword dies\n\nEs reiniciarà la vostra sessió.\n\nAquest dialeg se tancara en 10 segons"
                echo "changed"
        else
                zenity --timeout 10 --width=400 --error --title="Accés a la xarxa corporativa" --text="ERROR: No s'ha pogut canviar la contrasenya\n\nAquest dialeg se tancara en 10 segons"
                echo "password not changed"
        fi
}


PASSWORD=$(grep -i "^password=" $HOME/credentials | tr -d '\r'| tr -d '\n'| cut -f 2 -d "=" --output-delimiter=" ") 
#echo "Password llegit del fitxer de credencials: $PASSWORD"
passExpirat=$(echo $PASSWORD |  caib-test-expiracio-contrasenya | grep expire)
logger -t "prompt-chgpasswd-before-expiration-account($USER)" "passExpirat $passExpirat"
if [ "$passExpirat" != "" ];then
        num=$(echo $passExpirat | cut -d' ' -f 6)
        tipus=$(echo $passExpirat | cut -d' ' -f 7)
        logger -t "prompt-chgpasswd-before-expiration-account($USER)"  "Password expira en $num $tipus"
        case $tipus in
            "days"|"days."|"day.")
                        daysToExpirePassword=$num;
                        logger -t "prompt-chgpasswd-before-expiration-account" "INFO: ID=$(id -u) $USER's password age $AGE. daysToExpirePassword=$daysToExpirePassword"

                        if [ $daysToExpirePassword -lt 4 ];then
                                sleep 0.8 && zenity --timeout 5 --width=400 --info --title="Accés a la xarxa corporativa" --text="Usuari $USER, la vostra contrasenya caduca en $daysToExpirePassword dies; heu de canviar la contrasenya\n\nAquest dialeg se tancara en 5 segons" &
                                sleep 1;
                                resultatCanviPass=$(canviar_password);
                                until [ "$resultatCanviPass" != "changed" ];do
                                        resultatCanviPass=$(canviar_password);
                                done
                                echo "changed"
                                daysToExpirePassword=45
                        fi

                        if [ $daysToExpirePassword -lt  6 ] ;then
                                #Primer demanam si l'usuari vol canviar password
                                zenity --timeout=10 --width=480 --question --title="Canvi de contrasenya" --text="Usuari $USER, la vostra contrasenya caducarà en $daysToExpirePassword dies.\n\n\n\nLa voleu canviar ara?\n\n\n\nUn cop canviada haureu de reiniciar sessió al vostre equip.\n\nSi no sel·leccionau alguna opció en 10 segons se cancel·larà el procés de canvi de contrasenya." --cancel-label="Ara no"
                                case $? in
                                0)     canviar_password
                                        ;; 
                                1)     logger -t "prompt-chgpasswd-before-expiration" "INFO: l'usuari NO ha volgut canviar la contrasenya ara."
                                        ;;
                                5)     logger -t "prompt-chgpasswd-before-expiration" "INFO: l'usuari NO ha volgut canviar la contrasenya ara (timeout)."
                                        ;;
                                *)     logger -t "prompt-chgpasswd-before-expiration" "ERROR: resultat desconegut del prompt de canvi de contrasenya."
                                        ;;
                                esac
                        fi
                ;;
             *)
                logger -t "prompt-chgpasswd-before-expiration($USER)"  "ERROR: la expiracio no son dies, son: $tipus"                        
                ;;        
        esac

else
        logger -t "prompt-chgpasswd-before-expiration($USER)"  "Password NO expira prest"
fi

