#!/bin/sh


# TODO: consultar al seycon si la màquina existeix, si no existeix emprar només pam-kerberos i no winbind!


#El set -e és per a que si alguna comanda falli, s'aturi la instal·lació (comanda que no estigui dins un (if/test) )
set -e 

#Si debug no està definida, la definim
if [ -z $DEBUG ]; then DEBUG=1; fi
if [ "$DEBUG" -ge 3 ]; then
    # trace output
    set -x
fi


PKG=linuxcaib

#Variables configuració 
BACKUP_DATE=$(date +%Y%m%d_%H%M%S)
DIR_BACKUP_CONF="/opt/caib/linuxcaib/conf-backup/"$2""$BACKUP_DATE"/"

case "$1" in
    configure)

	if [ ! -d /tmp/install-linuxcaib-backup/ ];then
		mkdir /tmp/install-linuxcaib-backup/
	fi

	[ -f /etc/nsswitch.conf ] && cp /etc/nsswitch.conf /tmp/install-linuxcaib-backup/
	[ -f /etc/lightdm/lightdm.conf ] && cp /etc/lightdm/lightdm.conf /tmp/install-linuxcaib-backup/
	[ -d /etc/pam.d/common-auth ] && cp /etc/pam.d/common* /tmp/install-linuxcaib-backup/
	[ -f /usr/share/pam-configs/unix ] && cp /usr/share/pam-configs/unix /tmp/install-linuxcaib-backup/
	[ -f /usr/share/pam-configs/pam_script ] && cp /usr/share/pam-configs/pam_script /tmp/install-linuxcaib-backup/
	[ -f /usr/share/pam-configs/krb5 ] && cp /usr/share/pam-configs/krb5 /tmp/install-linuxcaib-backup/
	[ -f /usr/share/pam-configs/winbind ] && cp /usr/share/pam-configs/winbind /tmp/install-linuxcaib-backup/


	#Desactivam la configuració de libpam-scripts per defecte ERROR: no funciona!!!!
	[ -f /usr/share/pam-configs/pam_script ] && sed -i 's/Default: yes/Default: no/g' /usr/share/pam-configs/pam_script
	#Per ara eliminam el fitxer de configuració de libpam-script
	[ -f /usr/share/pam-configs/pam_script ] && rm /usr/share/pam-configs/pam_script

	#Desactivam la configuració de kerberos-scripts per defecte ERROR: no funciona!!!!
	[ -f /usr/share/pam-configs/krb5 ] && sed -i 's/Default: yes/Default: no/g' /usr/share/pam-configs/krb5
	#Desactivam la configuració de winbind per defecte ERROR: no funciona!!!!
	[ -f /usr/share/pam-configs/winbind ] && sed -i 's/Default: yes/Default: no/g' /usr/share/pam-configs/winbind

	#Per ara eliminam el fitxer de configuració de libpam-script
	[ -f /usr/share/pam-configs/krb5 ] && rm /usr/share/pam-configs/krb5
	#Per ara eliminam el fitxer de configuració de libpam-script
	[ -f /usr/share/pam-configs/winbind ] && rm /usr/share/pam-configs/winbind

	#Script que configura el que cal un cop instal·lats els fitxers del paquet

	#Cream enlaços simbolics per pam-script
	ln -s -f /opt/caib/linuxcaib/caib-pam-auth.sh  /usr/share/libpam-script/pam_script_auth
	#PER ARA NO EMPRAM SES_OPEN
	ln -s -f /opt/caib/linuxcaib/caib-pam-ses_open.sh  /usr/share/libpam-script/pam_script_ses_open
	#Hem d'afegir el close encara que no faci res.
	ln -s -f /opt/caib/linuxcaib/caib-pam-ses_close.sh  /usr/share/libpam-script/pam_script_ses_close
	#Aegim el passwd per interceptar els canvis de password.
	ln -s -f /opt/caib/linuxcaib/caib-pam-passwd.sh  /usr/share/libpam-script/pam_script_passwd


	#Configuram gdm (en teoria no cal, ja que hem d'emprar el lightdm però útil per instal·lacions 
	#no 100% normalitzades)
	#Cream enllaços per gdm (si esta instal·lat)
	if [ -d /etc/gdm3 ];then
                #https://help.gnome.org/admin/gdm/stable/configuration.html.en
                #Init, abans de presentar pantalla login
                mkdir -p /etc/gdm3/Init
		ln -s -f /opt/caib/linuxcaib/caib-lightdm-setup.sh /etc/gdm3/Init/:0
                
                #Mirar que convé més, si PostLogin o PreSession (PostLogin és més parescut a lightdm session-setup-script)
                #BUG?: ni a PostLogin ni a PreSession apareixen els diàlegs amb zenity!
                mkdir -p /etc/gdm3/PostLogin
		ln -s -f /opt/caib/linuxcaib/caib-lightdm-login.sh /etc/gdm3/PostLogin/:0
                
                #El PostSession s'executa quan ja s'han tancat les X!
		mkdir -p /etc/gdm3/PostSession
                ln -s -f /opt/caib/linuxcaib/caib-lightdm-logout.sh /etc/gdm3/PostSession/:0
		#faltaria configurar greeter etc. de gdm3
	fi

	#Configuram el servidor de temps de la CAIB.
	if [ -f /etc/ntp.conf ]; then
		cp /etc/ntp.conf /tmp/install-linuxcaib-backup/
                TIMESERVER=$(grep -m 1 "^server" /etc/ntp.conf)
                if [ "$TIMESERVER" != "server timesrv.caib.es" ];then
                        #Hem d'afegir el timeserver de la CAIB al principi.
                        sed -i "s/^$TIMESERVER/# Servidor de temps de la CAIB\nserver timesrv.caib.es\n$TIMESERVER/g" /etc/ntp.conf
                fi
	else
		echo "WARNING: no he pogut afegir el servidor de temps de la CAIB"
		echo "Si l'hora no és correcte no podreu fer login"
	fi

	#Configuram el lightdm
	#Ens asseguram que no hi hagi autologin activat
	for fitx in $(rgrep -l "autologin-user=true" /etc/lightdm/);do
		echo "Deshabilitam autologin d'usuari configurat al fitxer: $fitx"
		cp $fitx /tmp/install-linuxcaib-backup/
		sed 's/autologin-user=true/autologin-user=false/g' $fitx -i
	done

	#Personalització del lightdm-gtk-greeter.conf
	if [ -f /etc/lightdm/lightdm-gtk-greeter.conf ];then
		if (! grep /usr/share/images/caib/backgroundDefault.jpg /etc/lightdm/lightdm-gtk-greeter.conf >/dev/null)  ;then
		        #Si hi ha el background per defecte actualitzam el background 	
		        #Primer comentam el background anterior
		        sed -i 's/^background=/#prelinuxcaibbackground=/g' /etc/lightdm/lightdm-gtk-greeter.conf
			#Ara afegim el background de la caib
		        echo "background=/usr/share/images/caib/backgroundDefault.jpg" >> /etc/lightdm/lightdm-gtk-greeter.conf

		        #Primer comentam el show-indicators anterior
		        sed -i 's/^show-indicators=/#prelinuxcaibshow-indicators=/g' /etc/lightdm/lightdm-gtk-greeter.conf
			#Ara afegim la personalització de la caib
		        echo "show-indicators=~host;~a11y;~language;~session;~power" >> /etc/lightdm/lightdm-gtk-greeter.conf

		        #Primer comentam el screensaver-timeout anterior
		        sed -i 's/^screensaver-timeout=/#prelinuxcaibscreensaver-timeout=/g' /etc/lightdm/lightdm-gtk-greeter.conf
			#Ara afegim la personalització de la caib
		        echo "screensaver-timeout=300" >> /etc/lightdm/lightdm-gtk-greeter.conf
		fi
	fi

	#Configuram valors aplicacions per defecte

	#salvapantalles xscrensaver  -- /etc/X11/app-defaults/XScreenSaver
	if [ -f /etc/X11/app-defaults/XScreenSaver ]; then
	   cp /etc/X11/app-defaults/XScreenSaver /tmp/install-linuxcaib-backup/
	   sed -i 's/^*timeout:.*/*timeout:               0:10:00/g' /etc/X11/app-defaults/XScreenSaver
	   sed -i 's/^*lock:.*/*lock:                  True/g' /etc/X11/app-defaults/XScreenSaver
	   sed -i 's/^*lockTimeout:.*/*lockTimeout:           0:00:00/g' /etc/X11/app-defaults/XScreenSaver
	   sed -i 's/^*passwd.login.label:.*/*passwd.login.label:               Nova sessio usuari administrador/g' /etc/X11/app-defaults/XScreenSaver
	   sed -i 's/^*passwd.heading.label:.*/*passwd.heading.label:               Estacio treball CAIB/g' /etc/X11/app-defaults/XScreenSaver

	   sed -i 's/^*passwd.body.label:.*/*passwd.body.label:               Posau la vostra contrasenya per desbloquejar la estacio de treball o "Canviar a administrador"./g' /etc/X11/app-defaults/XScreenSaver

	   sed -i 's/^*passwd.user.label:.*/*passwd.user.label:               Usuari:/g' /etc/X11/app-defaults/XScreenSaver
	   sed -i 's/^*passwd.passwd.label:.*/*passwd.passwd.label:               Contrasenya:/g' /etc/X11/app-defaults/XScreenSaver
	   sed -i 's/^*passwd.unlock.label:.*/*passwd.unlock.label:               Desbloquejar/g' /etc/X11/app-defaults/XScreenSaver
	   #Com que empram ligtdm feim que el canvi d'usuari (administrdor) sigui del ligthdm
	   sed -i 's/^*newLoginCommand:.*/*newLoginCommand:               dm-tool switch-to-greeter/g' /etc/X11/app-defaults/XScreenSaver
	fi
	if [ -f /etc/X11/app-defaults/XScreenSaver-nogl ]; then
	   cp /etc/X11/app-defaults/XScreenSaver-nogl /tmp/install-linuxcaib-backup/
	   sed -i 's/^*timeout:.*/*timeout:               0:10:00/g' /etc/X11/app-defaults/XScreenSaver-nogl
	   sed -i 's/^*lock:.*/*lock:                  True/g' /etc/X11/app-defaults/XScreenSaver-nogl
	   sed -i 's/^*lockTimeout:.*/*lockTimeout:           0:00:00/g' /etc/X11/app-defaults/XScreenSaver-nogl
	   sed -i 's/^*passwd.login.label:.*/*passwd.login.label:		Canviar a administrador/g' /etc/X11/app-defaults/XScreenSaver
	   #Com que empram ligtdm feim que el canvi d'usuari (administrdor) sigui del ligthdm
	   sed -i 's/^*newLoginCommand:.*/*newLoginCommand:               dm-tool switch-to-greeter/g' /etc/X11/app-defaults/XScreenSaver
	fi


	#Actualitzam configuració de PAM
	echo "Configurant autenticació (pam)"
	pam-auth-update --package

	echo "Deshabilitam regles del firewall"
	iptables -F
	iptables -X
	iptables -t nat -F
	iptables -t nat -X
	iptables -t mangle -F
	iptables -t mangle -X
	iptables -P INPUT ACCEPT
	iptables -P FORWARD ACCEPT
	iptables -P OUTPUT ACCEPT

	#només UBUNTU, deshabilitam apport per a que no mostri missatges de crashos a l'usuari.
	#http://www.binarytides.com/ubuntu-fix-system-program-problem-error/
	if [ -f /etc/default/apport ];then
		cp  /etc/default/apport  /tmp/install-linuxcaib-backup/
		sed 's/^enabled=1/enabled=0/' /etc/default/apport -i
	fi

	#LOCALITZACIÓ de l'estació de treball 
	#Comprovam/definim el timezone
	#De totes maneres no és molt important ja que estarà a les instruccions d'instal·lació i hauria d'estar bé.
	if [ -f /usr/bin/timedatectl ];then
		#Si tenim timedatectl el definim ignorant el fus anterior.
		timedatectl set-local-rtc 0
		timedatectl set-timezone Europe/Madrid
	else
		#WARNING: Cercar alternativa a timedatectl.
		if [ -f /etc/timezone ]; then
		  fusHorari=`cat /etc/timezone`
		elif [ -h /etc/localtime]; then
		  fusHorari=`readlink /etc/localtime | sed "s/\/usr\/share\/zoneinfo\///"`
		else
		  checksum=`md5sum /etc/localtime | cut -d' ' -f1`
		  fusHorari=`find /usr/share/zoneinfo/ -type f -exec md5sum {} \; | grep "^$checksum" | sed "s/.*\/usr\/share\/zoneinfo\///" | head -n 1`
		fi
		if [ "$fusHorari" != "Europe/Madrid" ];then
		       echo "ERROR: el fus horari actual és: $fusHorari. Assegurau-vos que el fus horari sigui 'Europe/Madrid' mitjançant 'dpkg-reconfigure tzdata'"
		fi
	fi


	#Configuracions diverses

	#Deshabilitar avis de nova release lts (ubuntu)
	#http://ubuntuforums.org/showthread.php?t=1341711
	if [ -f /etc/update-manager/release-upgrades ];then
		sed -i 's/^Prompt=.*/Prompt=never/g' /etc/update-manager/release-upgrades
	fi
	#Per a que tampoc els mostri en fer login via consola
	if [ -f /etc/update-motd.d/91-release-upgrade ];then
		rm /etc/update-motd.d/91-release-upgrade
	fi

	#Windowitzar el Linux (definir noms aplicacions igual que windows)
	#Ubuntu ???? old????
	if [ -f /usr/bin/gcalctool ];then
		update-alternatives --install /usr/bin/calc calculadora  /usr/bin/gcalctool 50
	fi

	#Debian
	if [ -f /usr/bin/gnome-calculator ];then
		update-alternatives --install /usr/bin/calc calculadora  /usr/bin/gnome-calculator 50
	fi

	#Mirar si emprar kolourpaint4... molt millor
	if [ -f /usr/bin/gpaint ];then
		update-alternatives --install /usr/bin/paint dibuixar  /usr/bin/gpaint 50
	fi
	#Fer que "control" obri el "panel de control" de gnome.

	#Fer-ho primer amb gnome-settings-manager si hi és
	#En principi emprarem gnome o sigui que ha de ser "gnome-settings-manager" ???
	if [ -f /usr/bin/xfce4-settings-manager ];then
		update-alternatives --install /usr/bin/control control-panel  /usr/bin/xfce4-settings-manager 50
	fi

	if [ -f /usr/bin/gnome-settings-manager ];then
		update-alternatives --install /usr/bin/control control-panel  /usr/bin/gnome-settings-manager 50
	fi

	#Feim que gnome-flashback sigui el session manager per defecte.
	if [ -f /usr/lib/gnome-panel/gnome-session-flashback ];then
		update-alternatives --set x-session-manager /usr/lib/gnome-panel/gnome-session-flashback
	fi
	#També es podrien crear alternatives per coses de configuració comunes...
	#per exemple: caib-configura-salvapantalles, caib-esborrar-temporals, caib-.... així s'independitzaria el suport
	#del Linux subjaent.

	#FI Windowitzar el Linux

	#Cream carpeta per còpia de seguretat dels fitxers que l'instal·lador ha anat posant dins /tmp/install-linuxcaib-backup/ dins /opt/caib/linuxcaib/conf-backup/$DATA

	#Configuració ShiroKabuto
	#Donam d'alta SENSE password, fins que no es faci el primer login no tendrà password!!!!
	#Detectar si el hostname acaba en "l", aleshores suposarem que es un alias per una màquina linux que NO podrà actualitzar el shirokabuto
	if (! awk -F':' '{ print $1}' /etc/passwd |grep -q ShiroKabuto);then
		#No existeix usuari shirokabuto, el cream
		adduser --force-badname --disabled-login --quiet --gecos "Usuari local ShiroKabuto - SEU, suport-77070,,," ShiroKabuto
		adduser ShiroKabuto sudo
		#Feim que la contrasenya no caduqui
		chage -I -1 -m 0 -M 99999 -E -1 ShiroKabuto
	fi

	#Impedim que ShiroKabuto entri per SSH. Se suposa que només és usuari LOCAL.
	if [ "$(grep DenyUsers /etc/ssh/sshd_config | grep -q ShiroKabuto && echo SI)" = "" ];then
		#Hem d'afegir el DenyUsers
		if [ "$(grep -q DenyUsers /etc/ssh/sshd_config &&  echo SI)" = "SI" ];then
		        #Ja hi ha DenyUsers, hem d'afegir ShiroKabuto
		        denyUsers=$(grep DenyUsers /etc/ssh/sshd_config)
		        sed '/DenyUsers/d' /etc/ssh/sshd_config -i
		        echo "$denyUsers ShiroKabuto" >> /etc/ssh/sshd_config
		else
		        echo "DenyUsers ShiroKabuto" >> /etc/ssh/sshd_config
		fi
		echo "Deshabilitat l'accés de ShiroKabuto per SSH."
	fi

	#Si la màquina NO és un portàtil, deshabilitam la hibernació i sleep
	if ! laptop-detect;then
		echo "Postinst: NO es un portàtil, deshabilitant sleep i hibernació"
		#ERROR: no basta, a ubuntu 12.04 segueix apareixent el boto de "aturar temporalment" i atura la xarxa encara que no hiverni...
		chmod a-x /usr/sbin/pm-*    
	fi

	mkdir -p $DIR_BACKUP_CONF
	cp -r /tmp/install-linuxcaib-backup/* $DIR_BACKUP_CONF

	#No elimin conf-backups antics per tenir un registre de les instal·lacions

	#Feim els diverts dels fitxers de configuració
	#https://wiki.debian.org/ConfigPackages
	for f in krb5.conf puppet/puppet.conf apparmor.d/usr.sbin.cupsd
	do
		dpkg-divert --add --package ${PKG} --rename \
		        --divert /etc/$f.original /etc/$f
		if [ \! -e /etc/$f -o -L /etc/$f ]; then 
		        echo "Creant symlink /etc/$f cap /etc/CAIB/$f"
		        ln -sf /etc/CAIB/$f /etc/$f
		fi
	done


	#Possible millora: Si hi ha més de 1GB, baixam el nivell de swappiness
	#echo "# Decrease swap usage to a more reasonable level
	#vm.swappiness=10" >> /etc/sysctl.conf

	#Eliminam fitxers temporals
	rm -fr /tmp/install-linuxcaib-backup/

        #Modificam nsswitch per a que empri winbind!
        #passwd:         files winbind
        if ( grep ^passwd: /etc/nsswitch.conf|grep -q -v winbind );then
                echo "No hi ha winbind definit a passwd";
                passwd=$(grep ^passwd: /etc/nsswitch.conf);
                sed -i "s/$passwd/$passwd winbind/" /etc/nsswitch.conf
        fi
        #group:          files winbind
        if ( grep ^group: /etc/nsswitch.conf|grep -q -v winbind );then
                echo "No hi ha winbind definit a group";
                group=$(grep ^group: /etc/nsswitch.conf);
                sed -i "s/$group/$group winbind/" /etc/nsswitch.conf
        fi


	#Reiniciam samba
	set +e 
	echo "Reiniciant servidor samba - Si samba (nmbd, smbd i winbind) no estan aixecats no es podrà proseguir la instal·lació."
	if [ -r /etc/init.d/winbind ];then
		/etc/init.d/winbind stop
	fi

	if [ -r /etc/init.d/samba ];then
		#A ubuntu 14.04 NO funciona: service samba restart
		service nmbd stop
		service smbd stop
		service smbd start
		service nmbd start
	else
		if [ -r /etc/init.d/nmbd ];then
		        service smbd restart
		fi
		if [ -r /etc/init.d/smbd ];then
		        service nmbd restart
		fi
	fi
	if [ -r /etc/init.d/winbind ];then
		/etc/init.d/winbind start
	fi

	echo "Reiniciant servidor ssh"
	if [ -r /etc/init.d/ssh ];then
		service ssh restart
	fi

	#Generam les BBDD de dconf
	dconf update
	set -e 

	# TODO: FER QUE AIXO SE POSI AUTOMATIC! Automatically added by dh_installinit
	#if [ -x "/etc/init.d/caib-shutdown" ]; then
	#	update-rc.d caib-shutdown stop 20 0 6 . >/dev/null
	#fi
	# End automatically added section


	echo ""
	echo ""
	echo "ATENCIÓ! Heu de reiniciar el lightdm per a que agafi la nova configuració (service lightdm restart)."
	echo "Se recomanara reiniciar el lightdm des d'una consola virtual (CTRL-ALT-F1) loguejat com a root per a que, si alguna cosa no ha anat bé, ja estar loguejat."
	echo ""
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac


exit 0;
