#!/bin/sh

#El set -e és per a que si alguna comanda falli, s'aturi la instal·lació (comanda que no estigui dins un (if/test) )
set -e 

#Si debug no està definida, la definim
if [ -z $DEBUG ]; then DEBUG=0; fi
if [ "$DEBUG" -ge 3 ]; then
    # trace output
    set -x
fi

PKG=linuxcaib

#Script que prepara la eliminació de linuxcaib.

#Eliminam els enllaços simbolics per pam-script
[ -f /usr/share/libpam-script/pam_script_auth ] && rm /usr/share/libpam-script/pam_script_auth
[ -f /usr/share/libpam-script/pam_script_ses_open ] && rm /usr/share/libpam-script/pam_script_ses_open
[ -f /usr/share/libpam-script/pam_script_ses_close ] && rm /usr/share/libpam-script/pam_script_ses_close

#Feim els diverts dels fitxers de configuració
#https://wiki.debian.org/ConfigPackages
if [ "$1" = remove ] ; then
        for f in krb5.conf puppet/puppet.conf pam.d/polkit-1 apparmor.d/usr.sbin.cupsd
        do
                if [ -L /etc/$f ];then
                        echo "Eliminant fitxer de configuració propi: /etc/$f"
                        rm /etc/$f
                fi
                dpkg-divert --remove --package ${PKG} --rename \
                        --divert /etc/$f.original /etc/$f
        done

#        [ -f /etc/pam.d/polkit-1.original ] && ( cp /etc/pam.d/polkit-1.original /etc/pam.d/polkit-1 ; 
#        rm /etc/pam.d/polkit-1.original ; dpkg-divert --package $PKG --remove /etc/pam.d/polkit-1)

#        [ -f /etc/samba/smb.conf.original ] && ( cp /etc/samba/smb.conf.original /etc/samba/smb.conf ; 
#        rm /etc/samba/smb.conf.original ; dpkg-divert --package $PKG --remove /etc/samba/smb.conf)

#        [ -f /etc/krb5.conf.original ] && ( cp /etc/krb5.conf.original /etc/krb5.conf ; 
#        rm /etc/krb5.conf.original ; dpkg-divert --package $PKG --remove /etc/krb5.conf)

#        [ -f /etc/puppet/puppet.original ] && ( cp /etc/puppet/puppet.original /etc/puppet/puppet.conf ; 
#        rm /etc/puppet/puppet.original ; dpkg-divert --package $PKG --remove /etc/puppet/puppet.conf)
fi

exit 0;
