#! /bin/sh

### BEGIN INIT INFO
# Provides:		caib-shutdown
# Required-Start:	
# Required-Stop:	$remote_fs $syslog $time $network
# Default-Start:	
# Default-Stop:		0 6
# Short-Description:	Script que s'executa en apagar o reiniciar una màquina normalitzada de la CAIB GNU/Linux
### END INIT INFO

PATH=/sbin:/usr/sbin:/bin:/usr/bin

. /lib/lsb/init-functions

#set -e


#Si debug no està definida, la definim
if [ -z $DEBUG ]; then DEBUG=0; fi


if [ -f /root/shutdown-init.txt ];then
        rm /root/shutdown-init.txt
        touch /root/shutdown-init.txt
fi

#http://askubuntu.com/questions/250171/logout-scripts-not-completed-on-shutdown-reboot

#Script que s'executa en fer shutdown o reboot
#PRE-requisits: cal que el session-cleanup-script del lightdm posi dins /run/caib-last-logout-user
#el codi de l'usuari que fa el logout.

echo "caib-init-shutdownn: env: $(env) " >> /root/shutdown-init.txt

if [ -r /var/run/caib-last-logout-user ];then
	USER_RUN=$(cat /var/run/caib-last-logout-user)
        log_action_msg "/var/run/caib-last-logout-user Existeix! L'usuaria que ha tancat/reiniciat és: $USER_RUN"         
        echo "Sabem usuari que ha tancat/reiniciat és: $USER_RUN"  >> /root/shutdown-init.txt
        sleep 10s;
else
	log_action_msg "/var/run/caib-last-logout-user no existent! No sabem quin usuari ha fet està apagant/reiniciant!"
        echo "no sabem usuari!"  >> /root/shutdown-init.txt
        sleep 10s;
        exit 1;
fi


if [ "$USER_RUN" = "" ];then
	log_action_msg "USER_RUN no existeix"
	if [ "$USER" != "root" ];then
		USER_RUN=$USER
		HOME="/home/$USER_RUN"
	else
		HOME="/root"
	fi
else
	HOME="/home/$USER_RUN"
fi

log_action_msg "Emprant home=$HOME"
echo "Emprant home=$HOME" >> /root/shutdown-init.txt

log_action_msg "Fent el shutdown/reboot de la CAIB de l'usuari $USER_RUN usuari que executa aquest script: $USER"

#ALERTA! no podem emprar "id" ja que el winbind està aturat i ens dirà que no existeix l'usuari!
#echo "1 $USER_RUN id=$(id $USER_RUN 2>&1 )">> /root/shutdown-init.txt
#echo "$USER_RUN id=$(id $USER_RUN 2>&1)">> /root/shutdown-init.txt
#echo "$USER_RUN gid=$(id $USER_RUN -gn 2>&1)">> /root/shutdown-init.txt
#USER_GID=$(id $USER_RUN -gn)

if [ -f $HOME/shutdown-init.txt ];then
        rm $HOME/shutdown-init.txt
fi
touch $HOME/shutdown-init.txt
chown $USER_RUN:$USER_RUN $HOME/shutdown-init.txt

stamp=`/bin/date +'%Y%m%d%H%M%S %a'`
logger -t "linuxcaib-init-shutdown($USER_RUN)" -s  "Fent shutdown de l'usuari: $USER_RUN"
echo "$stamp env:\n$(env)"  >> $HOME/shutdown-init.txt
echo "$stamp iniciant shutdown init.d de l'usuari $USER" >> /root/shutdown-init.txt


if [ ! -f $HOME/.caib/MZN_SESSION ];then
        log_action_msg "caib-init-shutdown($USER_RUN) L'usuari $USER_RUN no estava loguejat al SEYCON, o ja hem fet logout de sessió"
        echo "L'usuari $USER_RUN no estava loguejat al SEYCON, o ja hem fet logout de sessió" >> /root/shutdown-init.txt
else
        log_action_msg "caib-init-shutdown($USER_RUN)  Logout de user=$USER_RUN"
        echo "caib-init-shutdown($USER)" "iniciant caib-aux-logout" >> /root/shutdown-init.txt
        sh /opt/caib/linuxcaib/caib-aux-logout.sh

	for p in $(seq 0 5) ; do
	    sleep 1
	    log_action_msg "Fent logout de $USER_RUN .... $p"
	done
# Realment l'únic important que cal fer és sincronitzar el perfil mòbil.
# la resta de coses que fa el caib-lightdm-logout/caib-xsession-logout son prescindibles, ja que s'està tancant
# la màquina i unitats montades i fitxers temporals en memòria desapareixeran. 
#sudo -u $USER_RUN /opt/caib/linuxcaib/caib-xsession-logout.sh
fi



start() {
	echo -n "Starting $DESC: "

}

stop() {
	echo -n "Stopping $DESC: "
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart|reload|force-reload)
		stop
		start
		;;
	*)
		echo "Usage: $0 {start|stop|restart|reload|force-reload}" >&2
		exit 2
		;;
esac



sleep 5;
exit 0;
